# Jekyll Resume Theme

# Site settings
title: Lewis Nguyen
email: email@domain.com
description: .
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Lewis Nguyen
job: UX Designer
location: Orange County, CA
languages: HTML, CSS and Javascript
# twitter_username: mattcouchman
# github_username:  mattcouchman
# codepen_username:  mattcouchman
email_address: lewisnguyenux@gmail.com

# Build settings
markdown: kramdown
