# Jekyll Resume Theme

# Site settings
title: Lewis Nguyen
email: email@domain.com
description: A.
baseurl: ""
url: "B"
name: C
job: D
location: E
languages: F
# twitter_username: mattcouchman
# github_username:  mattcouchman
# codepen_username:  mattcouchman
email_address: lewisnguyenux@gmail.com

# Build settings
markdown: kramdown
