# Jekyll Resume Theme

# Site settings
title: Lewis Nguyen
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Lewis Nguyen
job: UX Designer
location: Orange County, CA
languages: F
twitter_username: mattcouchman
github_username:  mattcouchman
codepen_username:  mattcouchman
linkedin_username: lewisnguyenux
email_address: lewisnguyenux@gmail.com

# Build settings
markdown: kramdown
